name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate snake animation
    steps:
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Rogue-Sensei-Dev
          outputs: |
      dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
