name: Generate Snake Animation (Dark Mode Only)

on:
  schedule:
    # Runs every 24 hours at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate snake.svg

    steps:
      - name: Generate GitHub contribution snake (Dark Mode)
        uses: Platane/snk@v3
        with:
          github_user_name: Rogue-Sensei-Dev
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push the generated SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
